# Generated by Django 5.0 on 2024-04-02 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='isgay',
            field=models.BooleanField(default=False, verbose_name=False),
            preserve_default=False,
        ),
    ]
