# Generated by Django 5.0 on 2024-04-02 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0002_data_isgay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='isgay',
            field=models.BooleanField(),
        ),
    ]
